version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: client-container
    ports:
      - "80:80"

