version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.fronten
    ports:
      - "80:80"
