FROM python:3.9-slim

ENV PYTHONPATH=/backend-app


WORKDIR /backend-app

COPY ./app/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/ ./app/
COPY . .


EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
