# Dockerfile for Flask Backend
FROM python:3.9-slim

ENV PYTHONPATH=/backend-app


WORKDIR /backend-app

# Copy requirements and install dependencies
COPY ./app/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY ./app/ ./app/
COPY . .


# Expose the Flask port
EXPOSE 5000

# Run Flask in production mode
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
